update_interval_seconds: 120
notification_template: |
  Der Stream ist online:
  {title}
  
  Aktuelles Spiel: {game}
  #twitch #mrpbot #noxp
game_switch_template: |
  Das Spiel wird gewechselt zu:  
  {game}
  
  #twitch #mrpbot #noxp
twitch:
  app_id:
  app_secret:
  watched_channel:
mastodon:
  instance: https://mastodon.social
  client_token:
  client_secret:
  access_token:
twitter:
  api_key:
  api_secret:
  access_token:
  access_token_secret:
discord:
  webhook:

